version: '2'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - mysql:db
  mysql:
    image: mysql
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    expose:
      - 3306
    volumes:
      - ./sql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=scry
      - MYSQL_DATABASE=scry
